# Tensorflow with Contrib.Learn 

In [34]:
import tensorflow as tf
import numpy as np
from sklearn.datasets import load_iris
iris = load_iris()
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [3]:
X = iris['data']

In [4]:
y = iris['target']

In [5]:
y.dtype

dtype('int32')

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.3)

In [8]:
feature_columns = [tf.contrib.layers.real_valued_column("", dimension=4)]

In [29]:
classifier = tf.estimator.DNNClassifier(feature_columns=feature_columns,
                                            hidden_units=[10, 20, 10],
                                            n_classes=3,
                                            model_dir="./output")

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': './output', '_master': '', '_save_checkpoints_secs': 600, '_task_type': 'worker', '_train_distribute': None, '_global_id_in_cluster': 0, '_num_ps_replicas': 0, '_service': None, '_evaluation_master': '', '_keep_checkpoint_max': 5, '_num_worker_replicas': 1, '_is_chief': True, '_tf_random_seed': None, '_save_checkpoints_steps': None, '_device_fn': None, '_session_config': None, '_save_summary_steps': 100, '_log_step_count_steps': 100, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x00000295E5DE7C50>, '_keep_checkpoint_every_n_hours': 10000, '_task_id': 0}


In [43]:
train_input_fn = tf.estimator.inputs.numpy_input_fn(x={"x": np.array(X)},y=np.array(y),num_epochs=None,shuffle=True)
classifier.train(input_fn=train_input_fn, steps=100)

INFO:tensorflow:Calling model_fn.


ValueError: Feature  is not in features dictionary.

In [41]:
iris_predictions = list(classifier.predict(X_test))

TypeError: unsupported callable

In [26]:
from sklearn.metrics import classification_report, confusion_matrix

In [27]:
print(classification_report(y_test, iris_predictions))
print(confusion_matrix(y_test, iris_predictions))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        19
          1       0.00      0.00      0.00        12
          2       0.54      1.00      0.70        14

avg / total       0.59      0.73      0.64        45

[[19  0  0]
 [ 0  0 12]
 [ 0  0 14]]


C:\Users\samee\Anaconda3\envs\tf\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
